### PR TITLE
Use fenced code block to have syntax highlighting

### PR DESCRIPTION
**Pull request by adius**

### CODE REVIEW

**Comment by zkat** [comment]
LGTM.

**Comment by othiym23** [comment]
Landed in 5271229ee7c810217dd51616c086f5d9ab224581, included in `nopt@4.0.0`. Thanks for the patch!

**Comment by adius** [comment]
Thanks, but c0d156f229f9994c5dfcec4a8886eceff7a07682 already destroyed it 😭🙈

**Comment by othiym23** [comment]
uugh... merge conflicts! This is what I get for merging so many patches at once! I'all fix this shortly. Thanks for the follow up!

**Comment by othiym23** [comment]
Fixed and pushed out as `nopt@4.0.1` – thanks again for letting me know it got messed up!

**Pull request closed without merging**
